= Couchbase Tutorials
:page-layout: landing-page-tutorials
:page-role: tiles
:!sectids:

include::tutorials:ROOT:partial$_attributes-local.adoc[]

= Couchbase Tutorials
++++
<div class="card-row">
++++

[.column]
====== {empty}
[.content]
Go hands-on with Couchbase Tutorials.
The tutorials listed on this page are available as reference samples. In addition to these tutorials, Couchbase Documentation also provides Getting Started guides as part of the product documentation.

[.column]
====== {empty}
[.media-left]
pass:[<i class="fas fa-book-reader fa-7x"></i>]

++++
</div>
++++

== Tutorials
++++
<div class="card-row two-column-row">
++++
[.column]
[.data-filter-column]
====== {empty}
++++
<div data-category="beginner developer" class="sub-heading two-column-heading">
<h3 class="text-color-brand-blue-secondary">Couchbase Capella First-Timer Tutorial Series</h3>
<div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Developer</span>]
++++
</div>
</div>
++++
[.content]

This series of “First Timer” tutorials is intended to get you going quickly with your Couchbase Capella FREE Trial and provide a whirlwind tour of important Couchbase Capella capabilities at a high level.

xref:cbc-self-service-trials:index.adoc[Start Here]

++++
<div class="other-info-list">
++++

[.box]
[.component]

.Component
* Couchbase Capella

++++
</div>
++++


[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner java nodejs developer"  class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Get Started with Community Edition</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Developer</span>]
++++
        </div>
    </div>
++++
[.content]

Just getting started with Couchbase and using Couchbase Community Edition(CE)? Start here. This currently covers basic installation and querying along with Java, NodeJS, and Mobile development.

xref:getting-started-ce:index.adoc[Start Here]

++++
<div class="other-info-list">
++++

[.box]
.Component
* Server 6.5 Community Edition
* Sync Gateway 2.7
* Couchbase Lite 2.7

[.box]
.Languages
* Java
* Node.js

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
<div data-category="beginner java nodejs dotnet developer" class="sub-heading two-column-heading">
<h3 class="text-color-brand-blue-secondary">Developer Bootstrap Exercises</h3>
<div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Developer</span>]
++++
</div>
</div>
++++
[.content]

Are you a developer interested in a fast start with Couchbase? This expanding set of basic first-steps exercises provide a fast track from zero to your substantial interactions with Couchbase Server using your favorite development frameworks and IDEs.

xref:quick-start:quickstart-docker-image-manual-cb65.adoc[Start Here]

++++
<div class="other-info-list">
++++

[.box]
[.component]

.Component
* Server 6.5 CE or EE
* SDK 3.0 or 2.x

[.box]
[.languages]

.Languages
* Java
* Node.js
* .NET

++++
</div>
++++


[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner swift mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Get Started with Couchbase Mobile on iOS</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

The series of tutorials demonstrates the core capabilities of Couchbase Mobile with an iOS app:

* Standalone: Learn about Couchbase Lite's database and CRUD operations.
* Query: Explore Couchbase Lite's query capabilities.
* Sync: Couple Couchbase Lite with Sync Gateway to tap into the power of data sync.

++++
<div class="other-info-list">
++++

[.box]
.Components Used
* Server 7.0
* Couchbase Lite 3.0
* Sync Gateway 3.0

[.box]
.Languages
* iOS 12
* Swift 5.5
* Xcode 12.5

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner android mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Get Started with Couchbase Mobile on Android</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

The series of tutorials demonstrates the core capabilities of Couchbase Mobile with an Android app:

* "Standalone": database and CRUD operations.
* "Query": querying capabilities.
* "Sync": use of Sync Gateway for data sync between clients.


++++
<div class="other-info-list">
++++

[.box]

* xref:standalone@userprofile-couchbase-mobile:userprofile:android/userprofile_basic.adoc[Standalone]
* xref:query@userprofile-couchbase-mobile:userprofile:android/userprofile_query.adoc[Query]
* xref:sync@userprofile-couchbase-mobile:userprofile:android/userprofile_sync.adoc[Sync]


[.box]
.Component
* Server 5.5
* Couchbase Lite 2.6
* Sync Gateway 2.6

[.box]
.Languages
* Java

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner c# mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Get Started with Couchbase Mobile on Xamarin</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

The series of tutorials demonstrates the core capabilities of Couchbase Mobile with a Xamarin app:

* "Standalone": database and CRUD operations.
* "Query": querying capabilities.
* "Sync": use of Sync Gateway for data sync between clients.


++++
<div class="other-info-list">
++++

[.box]

* xref:standalone@userprofile-couchbase-mobile:userprofile:xamarin/userprofile_basic.adoc[Standalone]
* xref:query@userprofile-couchbase-mobile:userprofile:xamarin/userprofile_query.adoc[Query]
* xref:sync@userprofile-couchbase-mobile:userprofile:xamarin/userprofile_sync.adoc[Sync]


[.box]
.Component
* Server 5.5
* Couchbase Lite 2.1
* Sync Gateway 2.1

[.box]
.Languages
* C#

++++
</div>
++++

// BEGIN include P2P sync over websocket tutorials - one entry per language/platform
:param-language: Swift
:param-platform: iOS
:param-module: swift
:param-version: 2.8
include::partial$p2p-sync-entry-skeleton.adoc[]

// Uncomment the following as the platforms are available

// :param-language: Java
// :param-module: java
// :param-version: 2.8
// include::partial$p2p-sync-entry-skeleton.adoc[]

// :param-language: Android (Java)
// :param-module: android
// :param-platform: Android
// :param-version: 2.8
// include::partial$p2p-sync-entry-skeleton.adoc[]

:param-language: C#
:param-platform: Xamarin
:param-module: dotnet
:param-version: 3.0.0-beta02
include::partial$p2p-sync-entry-skeleton.adoc[]

// END include P2P sync over websocket tutorials - one entry per language/platform


// [.column]
// [.data-filter-column]
// ====== {empty}
// ++++
//     <div data-category="beginner swift mobile developer" class="sub-heading two-column-heading">
//         <h3 class="text-color-brand-blue-secondary">Background Fetch with Couchbase Lite on iOS</h3>
//         <div class="filter-info">
// ++++
// pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
// ++++
//         </div>
//     </div>
// ++++
// [.content]

// This tutorial discusses how you can use iOS Background App Refresh capability to sync data when in the background.

// ++++
// <div class="other-info-list">
// ++++

// [.box]

// * xref:backgroundfetch@userprofile-couchbase-mobile:userprofile:background-fetch.adoc[Start Here]


// [.box]
// .Component
// * Server 5.5
// * Couchbase Lite 2.1
// * Sync Gateway 2.1

// [.box]
// .Languages
// * Swift

// ++++
// </div>
// ++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner swift java javascript mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Building a Cordova Plugin with Couchbase Lite</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

In this tutorial, you will learn how to use Couchbase Lite in a Cordova plugin for an Ionic project targeting iOS and Android.
The user Interface is written in JavaScript while the business logic and data model is written in native Swift/Java.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:hotel-lister:ios.adoc[Swift]
* xref:tutorials:hotel-lister:android.adoc[Java]

[.box]
.Component
* Couchbase Lite 2.1

[.box]
.Languages
* Swift
* Java
* Javascript

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner swift java javascript mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Building a React Native Module with Couchbase Lite</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

In this tutorial, you will learn how to use Couchbase Lite in a React Native project for iOS and Android.
The user Interface is written in JavaScript while the business logic and data model is written in native Swift/Java.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:hotel-finder:ios.adoc[Swift]
* xref:tutorials:hotel-finder:android.adoc[Java]

[.box]
.Component
* Couchbase Lite 2.6

[.box]
.Languages
* Swift
* Java
* Javascript

++++
</div>
++++


[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner swift mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Xcode playground for Couchbase Lite Query</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

A Xcode Playground to explore the Query API in Couchbase Lite 2.x. While the playground demonstrates the queries in swift, given the unified nature of the QueryBuilder API, you should be able to easily translate the queries to any of the other platform languages supported on Couchbase Lite.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:swift-playground:overview.adoc[Start Here]

[.box]
.Component
* Couchbase Lite 2.8.1

[.box]
.Languages
* Swift

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner android java dotnet mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Android Recycler Views with Couchbase Lite</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

This tutorial will demonstrate how you can use Couchbase Lite as a data source for Recycler Views in your Android application.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:university-lister:android.adoc[Start Here]

[.box]
.Component
* Couchbase Lite 2.1

[.box]
.Languages
* Java

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner java dotnet developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Using Couchbase Server as a User Profile Store</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Developer</span>]
++++
        </div>
    </div>
++++
[.content]

An comprehensive tutorial that demonstrates how to use Couchbase Server, Spring Data, Full-Text Search and Cross Data Center Replication (XDCR) to build a production-grade User Profile Store micro-service.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:profile-store:install.adoc[Start Here]
* xref:tutorials:profile-store:dotnet.adoc[.NET]
* xref:tutorials:profile-store:java.adoc[Java]

[.box]
.Component
* Couchbase Server 6.0

[.box]
.Languages
* Java
* .NET

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner java dotnet developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Using Couchbase Server as a User Profile Store</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Developer</span>]
++++
        </div>
    </div>
++++
[.content]

An comprehensive tutorial that demonstrates how to use Couchbase Server, Spring Data, Full Text Search, and Cross Data Center Replication (XDCR) to build a production-grade User Profile Store micro-service.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:profile-store:install.adoc[Start Here]
* xref:tutorials:profile-store:dotnet.adoc[.NET]
* xref:tutorials:profile-store:java.adoc[Java]

[.box]
.Component
* Couchbase Server 6.0

[.box]
.Languages
* Java
* .NET

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="intermediate swift android java c# mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Couchbase Mobile Workshop</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-intermediate}" alt="" />Intermediate</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

An in-depth walkthrough of the Couchbase Mobile capabilities on iOS, Android, Java (desktop) and .NET (UWP and Xamarin) platforms.
At the end of this multi-part workshop, you should have a good understanding of how to architect a solution using Couchbase Mobile, including data modeling, sync, access control, channels, database CRUD and the query API in Couchbase Mobile.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:mobile-travel-sample:introduction.adoc[Start Here]
* xref:tutorials:mobile-travel-sample:swift/installation/index.adoc[iOS]
* xref:tutorials:mobile-travel-sample:android/installation/index.adoc[Android]
* xref:tutorials:mobile-travel-sample:java/installation/index.adoc[Java]
* xref:tutorials:mobile-travel-sample:csharp/installation/index.adoc[.NET]

[.box]
.Component
* Couchbase Server 6.5
* Couchbase Lite 2.8
* Sync Gateway 2.8

[.box]
.Languages
* Swift
* Java (Android and Desktop)
* C#

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="intermediate javascript developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Customer 360 Data Ingestion</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-intermediate}" alt="" />Intermediate</h5><span>Developer</span>]
++++
        </div>
    </div>
++++
[.content]

The goal of a Customer 360 system is to deliver a single, consistent view of all your data in one platform within an enterprise where that data is split up between many different systems. This tutorial will be focusing mainly on getting a complete view of a customer/person.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:customer-360:ingestion.adoc[Retail]

[.box]
.Component
* Couchbase Server 6.0
* Kafka
* Docker

[.box]
.Languages
* Javascript

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="intermediate java c# developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Using Couchbase Server as a Session Store</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-intermediate}" alt="" />Intermediate</h5><span>Developer</span>]
++++
        </div>
    </div>
++++
[.content]

An in-depth tutorial that demonstrates how to use Couchbase Server for session storage.
You will learn how to read, write session data and query session data with N1QL for business insights.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:session-storage:install.adoc[Start Here]
* xref:tutorials:session-storage:aspnet.adoc[ASP.NET Core]
* xref:tutorials:session-storage:java.adoc[Java]

[.box]
.Component
* Couchbase Server 6.0

[.box]
.Languages
* C#
* Java

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="intermediate java developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Boosting Spring Data Performance with Couchbase</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-intermediate}" alt="" />Intermediate</h5><span>Developer</span>]
++++
        </div>
    </div>
++++
[.content]

Spring Data provides an easy programming model for data access in both relational and non-relational databases. It became very popular among Java/JVM developers because of the small learning curve and low codebase.

However, developers quite often run into performance issues while using it, this tutorial aims to explain some of the common problems and how to fix them.


++++
<div class="other-info-list">
++++

[.box]
* xref:tutorials:spring-data-indexes:spring-index.adoc[Start Here]


[.box]
.Component
* Spring Data

[.box]
.Languages
* Java

++++
</div>
++++

[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="intermediate java mobile developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">OpenID Connect with Sync Gateway</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-intermediate}" alt="" />Intermediate</h5><span>Mobile Developer</span>]
++++
        </div>
    </div>
++++
[.content]

A complete tutorial on how to set up an OpenID Connect authentication (using the implicit flow method) for Couchbase Sync Gateway.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:openid-connect-implicit-flow:index.adoc[Start Here]

[.box]
.Component
* Couchbase Server 6.5
* Couchbase Lite 2.7
* Sync Gateway 2.7
* Keycloak

[.box]
.Languages
* Java

++++
</div>
++++


[.column]
[.data-filter-column]
====== {empty}
++++
    <div data-category="beginner developer" class="sub-heading two-column-heading">
        <h3 class="text-color-brand-blue-secondary">Build Your Own Tutorial</h3>
        <div class="filter-info">
++++
pass:attributes[<h5><img src="{url-icon-beginner}" alt="" />Beginner</h5><span>Developer</span>]
++++
        </div>
    </div>
++++
[.content]

Looking to build a tutorial and share with the Couchbase community? Take a look at our tutorial template you could use as a starting point.

++++
<div class="other-info-list">
++++

[.box]

* xref:tutorials:tutorial-template:sample.adoc[Tutorial Template]

[.box]
.Component
* Couchbase Tutorials

[.box]
.Languages
* AsciiDoc

++++
</div>
++++

++++
</div>
++++
